services:
  tmx-moon:
    container_name: ${PROJECT_NAME:-tmx-moon}-c
    build: .
    image: ${PROJECT_NAME:-tmx-moon}:${PROJECT_VERSION:-latest}
    ports:
      - 3000:3005
    volumes:
      - .:/${PROJECT_NAME:-tmx-moon}
